[package]
name = "deadalus"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.16.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.9.0" }
# openzeppelin = { git = "https://github.com/phipsae/oz-cairo-contracts", branch = "main" }
starknet = "2.5.3"

[[target.starknet-contract]]
sierra = true 
casm = true
sierra-text = true 
casm-add-pythonic-hints = true

[tool.snforge]
exit_first = true


